chore: add backport config and added codespell pre-commit
agritheory/inventory_tools pull request #109
Opened 2024-08-12 07:13 UTC by MyuddinKhatri

issue - #83 

Added backport config - https://github.com/tibdex/backport
Labels to be added - `backport version-15` and `backport version-14`

Added pre-commit codespell

2024-08-12 10:12 UTC, Alchez requested changes

2024-08-12 10:12 UTC, Alchez commented on pyproject.toml
> +[tool.codespell]
Same as https://github.com/agritheory/cloud_storage/pull/78#discussion_r1713478400.

2024-08-13 05:30 UTC, Alchez approved these changes

2024-08-13 11:57 UTC, agritheory approved these changes

2024-08-13 11:57 UTC, merged