Faceted search
agritheory/inventory_tools pull request #44
Opened 2023-12-11 17:07 UTC by agritheory

2023-12-11 17:09 UTC, agritheory commented
@Alchez Can you branch and pick up changes for list view integration? That should be a PR to this branch. Main integration points should be inside `setFilterValues` in `FacetSearch.vue`. Which we should abstract to `api.js` anyway.

2024-02-26 16:30 UTC, agritheory commented
To Dos as of 2/26/24:

- [x] Make views configurable in Inventory Tools settings - `all-products`, Item List View, via `frappe.boot` #73 
- [x] Document and manually test Specification configuration workflow
- [x] Add helper on Item Group (to generate Specification Values for Items in that group)
- [x] Add helper on Item to edit that Item's Specification Values

2024-04-10 20:12 UTC, agritheory commented
@bhattdevarsh This looks great! A couple more things to incorporate:

- Reduce the width of the scrollbar on Firefox (this looks like a default width and I think we want it to be 75 or 80%)
- Let's add a collapse caret on the top right

![image](https://github.com/agritheory/inventory_tools/assets/18033666/b1b85b7d-6f86-4645-ac72-b53f6c6bf88f)

2024-04-11 21:26 UTC, bhattdevarsh commented
- Added collapsible div
- Managed Icon, onclick event and cursor pointer
- Added key value to searchComponent called `visible`
![filter_scroller_and_collapsable](https://github.com/agritheory/inventory_tools/assets/58166671/547659ae-9c53-4975-9cb4-9f0da97886ac)

- Made possible changes to customize scrollbar on Firefox
![firefox_Filter_Scroller](https://github.com/agritheory/inventory_tools/assets/58166671/20e69280-9a27-4b55-bb02-f3e0f3d38c80)

2024-04-22 07:17 UTC, Alchez requested changes

2024-04-22 07:17 UTC, Alchez commented on package.json
> -{
Why is this file being deleted?

2024-04-22 07:17 UTC, Alchez commented on inventory_tools/docs/faceted_search.md
> +An Inventory Tools for ERPNext. This allows user to list their product under `/all-products` and filter them with their specification
```suggestion
Faceted search works on top of ERPNext's shopping cart to add additional e-commerce controls for marketplace users. This feature allows you to list your products under `/all-products` and filter them based on their specifications.
```

2024-04-22 07:17 UTC, Alchez commented on inventory_tools/docs/faceted_search.md
> +Follow the steps to create your first listed product which allows multiple specification and it's variations.
```suggestion
Follow the steps to create your first listed product with multiple specifications and their variations.
```

2024-04-22 07:17 UTC, Alchez commented on inventory_tools/docs/faceted_search.md
> +      - Select the `Field` on which this should be applied (Can be left empty).
I think the mandatory/optional suggestion should be left to the form

```suggestion
      - Select the `Field` on which the attribute should be applied.
```

OR

```suggestion
      - Optionally select the `Field` on which the attribute should be applied.
```

2024-04-22 07:17 UTC, Alchez commented on inventory_tools/docs/faceted_search.md
> +      - Choose `Component` based one following explainations:
```suggestion
      - Choose a `Component` based on the following criteria:
```

2024-04-22 07:17 UTC, Alchez commented on inventory_tools/docs/faceted_search.md
> +          4. `AttributeFilter` If any other the mentioned above.
```suggestion
          1. `FacetedSearchColorPicker`: if the attribute is related to colors.
          2. `FacetedSearchDateRange`: if the attribute is related to date values.
          3. `FacetedSearchNumericRange`: if the attribute is related to numeric values.
          4. `AttributeFilter`: if the attribute doesn't belong to any of the above.
```

2024-04-22 07:17 UTC, Alchez commented on inventory_tools/docs/faceted_search.md
> +      - `Save` Specifications.
```suggestion
      - `Save` the Specification(s).
```

2024-04-22 07:17 UTC, Alchez commented on inventory_tools/docs/faceted_search.md
> +   - On Item page click `Actions` (Top Right) >  Click `Edit Specification` (This will prepopulate the specifications based on your selection, If not please select from the dropdown)
```suggestion
   - On Item page click `Actions` (Top Right) >  Click `Edit Specification`
     - This will try to pre-populate the specifications based on your selection. If no specifications are set, please select from the dropdown instead.
```

2024-04-22 07:17 UTC, Alchez commented on inventory_tools/docs/faceted_search.md
> +This is how you can create and manage your specification. you can go to `/all-products`, you will see listed Item and Filter(s) on left.
This is slightly confusing. Should these be separate paragraphs, or are they related?

2024-04-22 07:17 UTC, Alchez commented on inventory_tools/docs/faceted_search.md
> +`Specification` and `Specification Values` are reusable as far as the grouping of Items are done correctly, you may want to create new specification for different type goods.
For user documentation, I think we can avoid upper-casing doctype names when they're used in general sentences. What do you think @agritheory?

```suggestion
`Specification` and `Specification Values` are reusable as long as the grouping of items is done correctly. You may want to create new specifications for different types of goods.
```

2024-04-24 08:59 UTC, Alchez requested changes, later dismissed

2024-04-24 08:59 UTC, Alchez commented on inventory_tools/inventory_tools/faceted_search.py
> +from erpnext.e_commerce.api import *
Don't use [wildcard imports](https://peps.python.org/pep-0008/#imports). Explicitly import the functions that this file needs.

2024-04-24 08:59 UTC, Alchez commented on inventory_tools/public/js/faceted_search/FacetedSearch.vue
> +		frappe.ready(() => {
This will work on the website, but since this feature is also used in the desk, it errors out. Can the `frappe.ready` step happen before the component is mounted in the website, so that the component isn't making the decision on when to render?

PS: After removing the `frappe.ready` locally, here's how the component styling renders:

Default width:

![image](https://github.com/agritheory/inventory_tools/assets/13396535/f83ac0d3-f758-4069-a2a5-347a96f10725)

Full width:

![image](https://github.com/agritheory/inventory_tools/assets/13396535/e7e99a23-1e1d-49a5-837c-1a8d33eff278)

@agritheory what do you suggest?

2024-04-24 18:56 UTC, agritheory commented on inventory_tools/public/js/faceted_search/FacetedSearch.vue
> +					v-if="!comp.visible"
In this case we want `v-show` instead of `v-if``; "render and hide" versus "don't render"

2024-04-24 18:56 UTC, agritheory commented on inventory_tools/public/js/faceted_search/FacetedSearch.vue
> +		frappe.ready(() => {
@Alchez Yuck. That non-full width is... unflattering. I think we can style it better. The changes to make it render in the correct context at the correct time make sense.

2024-04-24 19:30 UTC, agritheory commented on inventory_tools/public/js/faceted_search/FacetedSearch.vue
> +		frappe.ready(() => {
@Alchez Also, please set up a bench per-app. We don't need customer apps leaking into this one.

2024-04-24 21:48 UTC, agritheory commented on inventory_tools/public/js/faceted_search/FacetedSearch.vue
> +		frappe.ready(() => {
@Alchez @bhattdevarsh I think the issue with this is re-using the bootstrap classes which has different modifications in the app vs portal views. We need to be more explicit and remove `list-unstyled`, `sidebar-menu`, etc

2024-04-24 22:00 UTC, agritheory commented
Still required for this to be considered complete:


> To Dos as of 2/26/24:
> 
> * [ ]  Make views configurable in Inventory Tools settings - `all-products`, Item List View, via `frappe.boot` [Load inventory_tools settings into frappe.boot #73](https://github.com/agritheory/inventory_tools/issues/73)
> * [x]  Document and manually test Specification configuration workflow
> * [ ]  Add helper on Item Group (to generate Specification Values for Items in that group)
> * [x]  Add helper on Item to edit that Item's Specification Values

@bhattdevarsh Can you add these last two features?

2024-04-28 10:30 UTC, bhattdevarsh commented
@agritheory @Alchez 

> * [ ]  Add helper on Item Group (to generate Specification Values for Items in that group)

I am thinking of a solution where we can use similar approach as helper on Item, Having a button called "Generate Specification Values" under Item Group and on click of that we fetch specification and attributes created for that group. Some Attributes can have some field mapped with it and some may not. For the mapped field attributes we can write a logic that auto-fetch the values from group items and for remaining we let user type it manually.

Attaching the image that demonstrates how the dialogue box may look like. please add/suggest necessary changes.

![image](https://github.com/agritheory/inventory_tools/assets/58166671/298d288c-68bb-445b-8931-786043ceda7b)

2024-04-28 13:35 UTC, agritheory commented
@bhattdevarsh I was thinking about this too and I think Item Group is actually the wrong place to put this, it should be on the specification itself. I like your approach and I think it makes sense to reuse or modularize the existing modal.

2024-04-30 10:16 UTC, bhattdevarsh commented on inventory_tools/inventory_tools/doctype/specification/specification.py
> +		frappe.get_doc({
We are losing information like Item(reference_doctype) and Item name(reference_name) while creating bulk specification values. We may need design changes to get expected results.

![image](https://github.com/agritheory/inventory_tools/assets/58166671/9fffc286-2530-4e75-b943-9644f5d7fa2a)

2024-05-06 19:49 UTC, bhattdevarsh commented
Previous commit carries solution to this issue-> https://github.com/agritheory/inventory_tools/issues/76

2024-05-23 15:38 UTC, agritheory commented
It does not appear as though the configuration for app/website visibility is working, filters do not appear to being set in the list view and the styling I think is not getting pulled in.

![image](https://github.com/agritheory/inventory_tools/assets/18033666/04ff53c0-f7e8-402f-8ed6-2fde98c8a3ce)

This feature is getting very lose but it isn't quite there yet. CC @Alchez @bhattdevarsh

2024-05-24 09:36 UTC, Alchez commented on inventory_tools/inventory_tools/doctype/specification/specification.py
> +	return
@agritheory @bhattdevarsh The older function was failing for me locally because the `tzname` variable was defaulting to "IST", but the `timezone` module couldn't parse that string. Maybe we could find an easier way of figuring out the epoch time from a given string?

2024-05-24 09:36 UTC, Alchez commented on inventory_tools/inventory_tools/faceted_search.py
> +		specification_items.update(item_codes)
@agritheory @bhattdevarsh The system was generating a list of sets which was causing the string display in the UI to become too long. I've changed the data type to a simple set of strings and the return value to a simple list of strings.

Let me know if that's the incorrect approach.

2024-05-24 09:36 UTC, Alchez commented on inventory_tools/public/js/faceted_search/FacetedSearch.vue
> +			listview.filter_area.clear(false)
@agritheory @bhattdevarsh Something is going wrong here that's causing the filter area to never get updated. Which means that the Item list view will load with no filters, but the UI will still show something like `6 filters`.

I'm guessing that's because the API has changed since I last worked on it.

2024-05-24 09:36 UTC, Alchez commented on inventory_tools/public/js/faceted_search/faceted_search.js
> +	if (!faceted_search.$search && $('#faceted-search').length === 0 && $('.filter-section').length > 0) {
I added the `$('.filter-section').length > 0` check here since the system was making way too many calls trying to mount the faceted search components.

2024-05-24 09:39 UTC, Alchez commented
@agritheory 

> It does not appear as though the configuration for app/website visibility is working, filters do not appear to being set in the list view

I've added a commit that should allow the filters to work, but I'm seeing weird UI issues with the applied filters that I've noted in a comment above.

> and the styling I think is not getting pulled in.

I couldn't see any stylesheets in the app, and I think all of it is coming from the vue files directly. I think they might just be incompatible or are being overridden?

2024-06-14 07:05 UTC, Alchez commented
@agritheory I couldn't get any of the faceted search components to affect the website or listview filters locally. Selecting any of the colours or changing the price filter keeps the current set of filters as is.

I ran the `before_test` function in this PR to setup the fixtures.

Also, for some reason, I can't see the black color in the color picker component

![image](https://github.com/agritheory/inventory_tools/assets/13396535/1633da67-c468-492b-b310-61263803b6fb)

2024-06-17 13:39 UTC, agritheory commented
@Alchez The tests are incomplete  - I want to test the various update insert APIs - and would need to be run in order to see any of the data

2024-08-04 19:01 UTC, agritheory commented
@Alchez Can you revisit the listview filter setting logic? Perhaps an API has changed. I recommend a clean install and then running `bench execute 'inventory_tools.tests.setup.create_demo_specification_values'` to setup the appropriate data.

2024-08-05 12:13 UTC, Alchez commented
@agritheory I was able to get the filters to run, but it seems like a couple of tests are still failing (CI is reporting incorrectly for some reason). Also, we should get on a call to confirm the final workflows before a merge.

2024-08-05 18:28 UTC, agritheory commented
@Alchez `/all-products` is now filtering correctly, though the sort order feature is still broken.  I am having an issue in the listview where the filter values are not being set correctly: there's a leading comma, and when de/reselecting the "brand" attribute, It doesn't seems to respond reasonably. Perhaps this the debounce function?

![image](https://github.com/user-attachments/assets/f89e7a79-9827-42cf-a246-58638a42fdfc)

I think we need to add a few compatibility features here:
When deselecting (no filters are set), the filters are not cleared. 
![image](https://github.com/user-attachments/assets/3e5ea132-68b2-4e25-83e8-70957e93d7aa)

When you click "Clear Filters" it does not reset the Faceted Search selections. We can listen on the clear filters click, I think, but we'd need to add a reset API to attribute filters as well. 
![image](https://github.com/user-attachments/assets/378917f0-e7ac-4952-a5a5-5e17f1ff1209)

2024-08-06 10:46 UTC, Alchez commented
@agritheory I've fixed up the bugs you mentioned. Can you give this another test please?

2024-08-12 15:42 UTC, merged