feat: Alternative workstation in job card and operation
agritheory/inventory_tools pull request #56
Opened 2024-02-16 15:26 UTC by viralkansodiya

https://www.awesomescreenshot.com/video/24855534?key=25bfb279c8d065cb1f8439b09812b27f

2024-02-17 11:12 UTC, viralkansodiya commented
@agritheory 

alternative workstation has been added to fixtures and change in setup.py

because of some conflict, i have to close old pull request, but same changes are available here

2024-02-20 15:10 UTC, agritheory requested changes
This looks feature complete to me, well done. The changes requested are generally about style and consistency within the app and latest versions of Frappe /ERPNext. 

Let's discuss the appropriate tests to include on the upcoming call, I think they'll be pretty straightforward.

2024-02-20 15:10 UTC, agritheory commented on inventory_tools/api.py
Let's move this to `inventory_tools/overrides/workstation.py` (new file), rather than have a general purpose file at the root level.

2024-02-20 15:10 UTC, agritheory commented on inventory_tools/api.py
> +	qb_data = (
Love to the query builder used, nice

2024-02-20 15:10 UTC, agritheory commented on inventory_tools/api.py
> +	workstation = frappe.db.sql(qb_data)
Perhaps use the `as_dict=True` argument which makes for the processing on line 24 easier to understand

2024-02-20 15:10 UTC, agritheory commented on inventory_tools/public/js/job_card_custom.js
> +		frm.trigger('set_workstation')
Can you refactor this to a standalone function rather than a class method? It's not wrong, I think it's less idiomatic to Frappe to do it this way. There are both in the Frappe and ERPNext codebases, but I think this pattern is much older.

2024-02-20 15:10 UTC, agritheory commented on inventory_tools/public/js/job_card_custom.js
> +		frm.set_query("workstation", function(doc) {
Personally, I prefer arrow functions `"workstation", doc => {`

2024-02-20 15:10 UTC, agritheory commented on inventory_tools/public/js/work_order_custom.js
> +cur_frm.fields_dict["operations"].grid.get_field("workstation").get_query = function(doc,cdt,cdn) {
~~This should move into a function that is called in onload and refresh~~

There's a cleaner API for this available in `frm.set_query`, I'll find an example and add it here.

2024-02-20 15:10 UTC, agritheory commented on inventory_tools/inventory_tools/custom/operation.json
> +   "fieldname": "custom_alternative_workstations",
Let's rename this to `alternative workstation` so that end users aren't confused about this being one of their own custom fields.

2024-02-20 15:10 UTC, agritheory commented on inventory_tools/inventory_tools/custom/operation.json
> +   "name": "Operation-custom_alternative_workstations",
Update this also after changing the fieldname. 

The easiest way to do this is to edit the JSON and reinstall, especially where all of the text fixtures are already written.

2024-02-20 15:10 UTC, agritheory commented on inventory_tools/inventory_tools/custom/operation.json
> +   "value": "[\"workstation\", null, \"data_2\", \"is_corrective_operation\", \"job_card_section\", \"create_job_card_based_on_batch_size\", \"quality_inspection_template\", \"column_break_6\", \"bat
Discussion point: I don't think that we should be including field order customizations in general purpose apps. I think its entirely appropriate in a customer-specific app.

2024-02-20 15:22 UTC, agritheory commented on inventory_tools/public/js/work_order_custom.js
> +cur_frm.fields_dict["operations"].grid.get_field("workstation").get_query = function(doc,cdt,cdn) {
Source: https://github.com/frappe/frappe/blob/develop/frappe/public/js/frappe/form/form.js#L1643

```js
frm.set_query("operations", "workstation", (frm, cdt, cdn) => {
	const row = locals[cdt][cdn]
	return {
		query: "inventory_tools.api.get_alternative_workstations",
		filters: {
			operation: row.operation
		}
	}
})
```
You can also pass in variables as needed, but this only matters


Example: https://github.com/agritheory/inventory_tools/blob/version-14/inventory_tools/public/js/uom_enforcement.js#L57

2024-02-20 15:24 UTC, agritheory reviewed
@viralkansodiya Please install pre-commit and run the following on the entire code base:

```bash
black . && prettier -w .
```

2024-02-20 15:40 UTC, agritheory commented on inventory_tools/api.py
> +	workstation = frappe.db.sql(qb_data)
Tuple is appropriate given that it's a search widget but let's include search fields in the response like `erpnext/controllers/queries.py`

2024-02-20 16:08 UTC, agritheory reviewed
Let's add a doc_event validation for valid alternative workstation

2024-02-21 06:18 UTC, viralkansodiya commented
<img width="615" alt="Cap" src="https://github.com/agritheory/inventory_tools/assets/141210323/eca0b98c-9da1-462b-90a2-80921bf53465">

2024-02-21 07:21 UTC, viralkansodiya commented on inventory_tools/public/js/job_card_custom.js
> +		frm.trigger('set_workstation')
I have changed pattern of the code
now there is separate function instead of trigger method

2024-02-21 07:25 UTC, viralkansodiya commented on inventory_tools/public/js/work_order_custom.js
> +cur_frm.fields_dict["operations"].grid.get_field("workstation").get_query = function(doc,cdt,cdn) {
Code has been updated with separate **function get_workstations** and also arrow key function

2024-02-21 09:24 UTC, viralkansodiya commented on inventory_tools/api.py
> +	workstation = frappe.db.sql(qb_data)
I have used searchfield in query please review once

2024-02-21 09:51 UTC, viralkansodiya commented on inventory_tools/api.py
removed api.py file and added new inventory_tools/overrides/workstation.py

2024-02-21 09:52 UTC, viralkansodiya commented on inventory_tools/inventory_tools/custom/operation.json
> +   "fieldname": "custom_alternative_workstations",
renamed fieldname  to alternative_workstation

2024-02-21 10:13 UTC, viralkansodiya commented
@agritheory 
Please Review the changes again

2024-03-01 17:39 UTC, merged