feat: allow user to bulk upload items with quantity to shoping cart
agritheory/inventory_tools pull request #70
Opened 2024-04-18 13:06 UTC by bhattdevarsh

https://github.com/agritheory/inventory_tools/issues/54

- New page `/bulk-order`
- Allow users to add item and quantity line by line 
- Allow users to add item and quantity as a bulk
- Process data and use existing `update_cart` def to update cart items.

### Possible Scope:

- [x]  Improvise UX
- [x]  Enqueue `update_cart` to handle large data

![bulk_order](https://github.com/agritheory/inventory_tools/assets/58166671/d5f32969-6bc2-45ec-9a7a-96ffd58bce64)

2024-04-19 06:10 UTC, Alchez requested changes
@agritheory @bhattdevarsh Is there a way to drop a Vue file into the `www` folder? Would that just work out of the box in version-14? Or would it require version-15's Vue 3 dependency?

2024-04-19 06:10 UTC, Alchez commented on inventory_tools/inventory_tools/bulk_order.py
> +	is_processed = bool(is_processed)
Is this required because the incoming data type can be string?

2024-04-19 06:10 UTC, Alchez commented on inventory_tools/inventory_tools/bulk_order.py
> +			sku_qty = line_item.split("\t")
```suggestion
			item_code, qty = line_item.split("\t")
```

2024-04-19 06:10 UTC, Alchez commented on inventory_tools/inventory_tools/bulk_order.py
> +def create_quotation(quote_data: str, is_processed: bool = False):
I think `is_processed` should be called `deserialize` or `deserialized` instead, since you want to check whether the `quote_data` needs to be converted back into a list.

2024-04-19 06:10 UTC, Alchez commented on inventory_tools/www/bulk-order.js
> +    var orderType = document.getElementById("order-type-button");
Don't use [var](https://dev.to/mindninjax/stop-using-var-for-declaring-variables-2p3a)

2024-04-19 06:10 UTC, Alchez commented on inventory_tools/www/bulk-order.html
> +        <button class="btn btn-primary mt-2 btn-sm btn-complete-signup w-60" onclick="createQuote(1)">
Just for slightly better readability:

```suggestion
        <button class="btn btn-primary mt-2 btn-sm btn-complete-signup w-60" onclick="createQuote(true)">
```

2024-04-19 07:47 UTC, bhattdevarsh commented
> @agritheory @bhattdevarsh Is there a way to drop a Vue file into the `www` folder? Would that just work out of the box in version-14? Or would it require version-15's Vue 3 dependency?

I think we had somewhat similar conversation before starting and concluded that we may not need Vue and just normal web page should do the job.

2024-04-22 07:02 UTC, Alchez requested changes
@bhattdevarsh see if you can install the pre-commit config. That should give you the warnings/errors quicker

2024-04-22 07:02 UTC, Alchez commented on inventory_tools/inventory_tools/bulk_order.py
> +		quote_data = json.loads(quote_data)
Use a different variable, and add some typing that should be expected as well (for example):

```suggestion
		quote_items: List[Dict] = json.loads(quote_data)
```

2024-04-23 21:08 UTC, bhattdevarsh commented
@Alchez  

New Update:
- Removed line-by-line form.
- Improvised code.
- Enqueued the `update_cart` def

Point of Discussion:
Exception handling not implemented at this stage: The form action is redirecting the user to python function, in case of any error on python function will show the traceback page instead of a popup. If that is fine, we can continue or else we can bring back the `.js` file which can handle the callback/error.

2024-04-24 06:10 UTC, Alchez commented
@bhattdevarsh this looks good to me. Is this PR ready to be merged, or are you adding something else as well?

2024-04-24 09:07 UTC, bhattdevarsh commented
> @bhattdevarsh this looks good to me. Is this PR ready to be merged, or are you adding something else as well?

good from my end.

2024-04-24 09:21 UTC, Alchez approved these changes

2024-04-24 09:22 UTC, Alchez commented
@agritheory @bhattdevarsh the test failure seems to be related to an error upstream with OS resolution. There's an issue created for it over at https://github.com/actions/runner-images/issues/7210.

2024-04-29 13:06 UTC, merged