Test alternative workstation
agritheory/inventory_tools pull request #80
Opened 2024-05-13 20:12 UTC by agritheory

#60 

- [ ]  Tests for alternative workstation
- [ ]  Tests for switching work orders between job card

2024-05-13 21:07 UTC, agritheory commented
Test for switching job cards will be added to the `issue_59` branch

2024-05-28 20:19 UTC, HKuz commented on inventory_tools/inventory_tools/overrides/workstation.py
> +		return execute(
Everything looks good, but I triggered one error stemming from this code block - when I turn the Inventory Tools Settings Allow Alternative Workstations feature OFF, create a Work Order (I used Ambrosia Pie), and try to change the workstation in the Gather Pie Filling operation, I got the following:

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1620, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/search.py", line 37, in search_link
    search_widget(
  File "apps/frappe/frappe/desk/search.py", line 108, in search_widget
    raise e
  File "apps/frappe/frappe/desk/search.py", line 85, in search_widget
    frappe.response["values"] = frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1620, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 808, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/__init__.py", line 2416, in wrapper
    return fn(**kwargs)
  File "apps/inventory_tools/inventory_tools/inventory_tools/overrides/workstation.py", line 35, in get_alternative_workstations
    return execute(
  File "apps/frappe/frappe/desk/reportview.py", line 65, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 201, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 245, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 239, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'tabWorkstation.operation' in 'where clause'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Workstation",
		"ignore_user_permissions": 0,
		"reference_doctype": "Work Order Operation",
		"query": "inventory_tools.inventory_tools.overrides.workstation.get_alternative_workstations",
		"filters": "{\"operation\":\"Gather Pie Filling Ingredients\",\"company\":\"Ambrosia Pie Company\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'tabWorkstation.operation' in 'where clause'\")"
}
```

If we only need the default workstation for the given operation (since alternatives is OFF), then we can run a `get_value` (I had to put the result in a double list to get it to match query result format expectations, so `return [[frappe.get_value("Operation", filters.get("operation"), "workstation")]]`. If we need more then we'll have to write a query similar to below.

2024-05-28 20:22 UTC, HKuz requested changes
One query error came up when I had the feature turned off - see comments on workstation.py.

2024-05-29 16:58 UTC, HKuz commented
Updated query code as discussed (pops filters before running `execute`). I also ran into a flake8 pre-commit error about backticks being deprecated (error W604), I added it to the `.flake8` file to ignore but let me know if I should use the `#noqa: W604` syntax inline instead.

Also, looks like we have our first track overrides warning - should I update for that in this PR or do that separately?

2024-05-29 17:11 UTC, agritheory commented
@HKuz Go ahead and evaluate the override warning.

2024-05-29 17:17 UTC, HKuz commented
@agritheory all good - latest erpnext changes in the commit didn't touch the method we're overriding. I merged in v-14 and made the update.

2024-05-29 17:42 UTC, HKuz approved these changes

2024-05-29 17:42 UTC, merged