refactor: pyproject.toml to poetry
agritheory/inventory_tools pull request #99
Opened 2024-06-22 08:15 UTC by MyuddinKhatri

Issue - #83 
- Refactor pyproject.toml to poetry

Added pre-commit config from test_utils - 
- validate_copyright
- clean_customized_doctypes
- validate_customizations
- validate_python_dependencies
- validate_javascript_dependencies\

Added pytest-coverage

2024-06-22 09:36 UTC, Alchez requested changes

2024-06-22 09:36 UTC, Alchez commented on pyproject.toml
> +mypy = "^1.10.0"
I think these should all be dev dependencies, since the base code doesn't require it

2024-06-24 08:37 UTC, Alchez approved these changes

2024-06-24 08:39 UTC, Alchez commented
@MyuddinKhatri the coverage comment didn't get generated, can you take a look at the Pytest check and see what's happening?

2024-07-08 14:37 UTC, MyuddinKhatri commented
@agritheory I think this is ready to review, will make the change for v15 release in another PR that is already up.

2024-07-13 11:04 UTC, merged